---
kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: test-init
  image: busybox
  commands:
  - chmod -R o+w /drone/src
- name: build
  image: node:10
  user: node
  commands:
  - npm install
  - npm test
- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-muuntaja
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: [master, test, melkehitys-1541]
    event: [push, tag]
---
kind: secret
name: docker_username
data: ouNENo4qD2NY65bcbgSWHj+1wDeSib6mQTrCUXr4jz3gUPWA52m9uxXUKFXPag8vfq4=
---
kind: secret
name: docker_password
data: 3tyBTSaydnGMaASeq29fz8CResuUBMOl6LAEkm3VEz/fD+UId3c1jLrniyq3qbETxTmEej5qP8MdyfNxn9DvzxeJPJuAky8KwEv766P17+AKcyZWBgBPCDlMh4E=
---
kind: signature
hmac: 7e4a9eed9427916411400254ca003fb484b2f53f3c12c92f428f8a1aa756ebf5

...
