language: node_js

node_js:
  - "7"
  - "node"
install:
  - npm install
after_script:
  - if test "$TRAVIS_NODE_VERSION" != "7";then exit 0;fi
  - if test $TRAVIS_BRANCH = "master";then JOB=$JOB_PROD;elif test $TRAVIS_BRANCH = "test";then JOB=$JOB_TEST;elif test $TRAVIS_BRANCH = "fix-ci";then JOB=$JOB_TEST;fi
  - if test ! -z $JOB;then curl -X POST --data "authtoken=$AUTH_TOKEN&argString=-checkout-reference $TRAVIS_COMMIT" https://melinda-ci.lib.helsinki.fi/api/14/job/$JOB/executions;fi
env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
    - JOB_PROD=af8274b8-e198-4054-8e04-1718279c0d13
    - JOB_TEST=05fdcba7-4e52-4981-97a3-d04247bc01ff
    - secure: "W4cbCJp7B7t2D+8Kc3Nt1slV6OslFLPL1CtmcQYCT0MLKJLYxivH08AaLmWDIixVLZdgTFJlqG0O3329hkg18FUTD+aLYtxl7R9Nc4iDRTv5jpavl/cu+5W0Xczf8e5m5lAKF5TZmSK521AZVgLLzZZrwvsfzYKaU1bwN/TYVc0i31KtjECC82G81kyXSsFUz/zwsnOukDos3I8j+R0RKycvGUXeZo+Hapv9doFAbDoJ0pDUUw9gnMa1DVRIG7Io54r+ymK2/mwnfwlClQTwgwo5lwnYJQ0TE8HzDhiwsTAwomxylCS6hVEfJ9mUYUDyh8H53r8CULfcEdM09OgaxWazNN4NhH/MaeaUaSt3LaaX8j5Y6YOfAaJAwyyfkGC3fzYghrT64mzdRVZPzSn2vt1f8l60kz22c4vJ+9g+PXfSrq0YzXchjtHMI4UMYZi7KNZDBQyBFvxpDYuPQtzX3tu/WV+3E3hCG34gWVOFNXAwP8baDpOzzuuaXt9CZQZPdfh1Xe9yc1eU4FEW5XzPPSxILF3iQ8+xvXsIbviA5reZqmPkzdZc7zkfFRZsWTf80liS5jwTAZyIGOR8mEod8o5CYLXLxQqBRWDL5eZwuvCvy7DxPuh4DB3ts1yalNlrW4qtY24fDj6zhpB6OLSVb7/sN8OZhOuKkcxOY3ehbLA="
