
language: node_js
node_js:
- 8
- node
install:
- npm install
script:
- npm test
- "BABEL_ENV=test mocha --require mock-local-storage --compilers js:babel-core/register --require ./frontend/test/test_bootstrap.js \"frontend/**/*@(.spec.js|.spec.jsx)\""
env:
  global:
  - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
